django_form/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^form/', include('form.urls')),
    url(r'^admin/', admin.site.urls),
]

form/urls.py
from django.conf.urls import url

from . import views
app_name = 'form'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^name/$', views.display, name='display'),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
    url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
]

form/models.py
from django.db import models

class Name(models.Model):
    s_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=200,default="")
    number= models.CharField(max_length=10,default="")
    

    def __str__(self):
        return self.name

form/forms.py
from django import forms
from .models import Name

class NameForm(forms.ModelForm):
    name = forms.CharField(label='Your name',max_length=100)
    city = forms.CharField(label='Your city',max_length=100)
    number = forms.CharField(label='Your number',max_length=100)

    class Meta:
        model = Name
        fields = ['name','city','number']

form/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.template import loader
from .forms import NameForm
from .models import Name

def index(request):
    return render(request, 'form/name.html')

def display(request):
    if request.method == 'POST':
        form=NameForm(request.POST)
        if form.is_valid():
            nameform=form.save(commit=False)
            nameform.name = request.POST['name']
            nameform.city = request.POST['city']
            nameform.number = request.POST['number']
            if request.POST['s_id']:
                obj = Name.objects.get(s_id=request.POST['s_id'])
                obj.name = request.POST['name']
                obj.city = request.POST['city']
                obj.number = request.POST['number']
                obj.save()
            else:
                nameform.save()
    query_results = Name.objects.all()
    return render(request, 'form/display.html', {'query_results': query_results})

def delete(request,id):
    Name.objects.filter(s_id=id).delete()
    query_results = Name.objects.all()
    return render(request, 'form/display.html', {'query_results': query_results})


def edit(request,id):
    #Name.objects.filter(s_id=id).delete()
    #query_results = Name.objects.all()
    obj = Name.objects.get(s_id = id)
    return render(request, 'form/name.html', {'name': obj.name, 'city':obj.city,'number':obj.number,'s_id':id})
    

form/templates/form/display.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  

</head>
<body>


<div class='container'>
<div class='col-md-offset-3 col-md-6'>
<h2>Table</h2>
  <table class="table table-striped">
    <thead>
      <tr>

        <th>id</th>
        <th>Name</th>
        <th>City</th>
        <th>Contact No.</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
    {% for user in query_results %}
        
      <tr>
        <td>{{ user.s_id }}</td>
        <td>{{ user.name }}</td>
        <td>{{ user.city }}</td>
        <td>{{ user.number }}</td>
        <td><a href="{% url 'form:edit' id=user.s_id %}" class="btn btn-info" >Edit</a></td>
        <td><a href="{% url 'form:delete' id=user.s_id %}" class="btn btn-danger" >Delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>


<!--
{% csrf_token %}
<h2>Your Name:- </h2><span><h3>{{ name }}</h3></span>
<h2>Your City:- </h2><span><h3>{{ city }}</h3></span>
<h2>Your Number:- </h2><span><h3>{{ number }}</h3></span>
-->
</div>
</body>
</html>

form/templates/form/name.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  

</head>
<body>



<div class="container">
<div class="col-md-offset-3 col-md-6">
  <h2>Form</h2>
  <form action="{% url 'form:display' %}" method="post">
      {% csrf_token %}
        
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" {% if name %}value={{ name }}{% endif %} id="name" placeholder="Enter Name" name="name" required>
        </div>
        <div class="form-group">
            <label for="city">City:</label>
            <input type="text" class="form-control" id="city" {% if city %}value={{ city }}{% endif %} placeholder="Enter City" name="city" required>
        </div>
        <div class="form-group">
            <label for="number">Contact No:</label>
            <input type="text" class="form-control" {% if number %}value={{ number }}{% endif %} id="number" placeholder="Enter Number" name="number" required>
        </div>
        <input type="text" style="display: none;" class="form-control" {% if s_id %}value={{ s_id }}{% endif %} id="s_id"  name="s_id" >
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
</div>
</body>
</html>